Feat/#102/users upload via csv
keeleinstituut/tv-authorization pull request #19
Opened 2023-05-03 14:25 UTC by kadmit

Task: https://github.com/keeleinstituut/tv-tolkevarav/issues/102

I implemented the functionality of uploading users via CSV. The solution includes 4 endpoints:

- Validation of the file. The endpoint returns a list of errors that were detected.
- Validation of the file row. The endpoint will be used to check changes after editing of incorrect row.
- Import the file. The endpoint will create institution users based on the data provided inside the file. In case the file has errors exception will be thrown.
- Endpoint for getting a list of institution users with filtering and sorting.

The task is not done fully because audit logs, tags, and vendor parts are not implemented yet.

2023-05-15 11:16 UTC, DanBondarenko requested changes
Hi @kadmit! I found some minor thingies and a few issues. Sorry for not doing the review earlier – in retrospect I could have reused some code that you already wrote.

2023-05-15 11:16 UTC, DanBondarenko commented on application/app/Rules/UserFullNameRule.php
> +    private const USER_NAME_REGEX = '/^[a-zõäöüšž\-]+(\s[a-zõäöüšž\-]+)$/iu';
**[non-blocker]** Hmm, is it confirmed that we won’t to allow characters used in non-Estonian names? If this is confirmed with analysis, no problem, but I imagine there might probably be users with names such as "Radwan Dąbrowski-Żądło" or "Jānis Bērziņš".

2023-05-15 11:16 UTC, DanBondarenko commented on application/database/factories/InstitutionUserFactory.php
> +            'phone' => $this->faker->numerify('+3725#######'),
**[compliment]** Nice!

2023-05-15 11:16 UTC, DanBondarenko commented on application/database/migrations/2023_05_02_133231_add_phone_to_institution_users_table.php
> +    }
**[blocker]** While doing another task, I heard from Birgit that is phone numbers are required for users. With that in mind, shouldn’t the column be non-nullable?

2023-05-15 11:16 UTC, DanBondarenko commented on application/app/Helpers/CsvReader.php
> +        $idx = 0;
**[non-blocker]**
```suggestion
```

2023-05-18 16:07 UTC, kadmit commented
@DanBondarenko thank you for the review! I fixed all of your suggestions, please take a look 🙂

2023-05-19 11:16 UTC, DanBondarenko commented
> @DanBondarenko thank you for the review! I fixed all of your suggestions, please take a look 🙂

@kadmit Thank you for the changes and your patience! Looks great. Approving. :)

2023-05-19 11:16 UTC, DanBondarenko approved these changes

2023-05-19 13:52 UTC, thenouan approved these changes

2023-05-19 13:58 UTC, merged