#139, #145, #147: Database schema, model logic and scheduled jobs
keeleinstituut/tv-authorization pull request #28
Opened 2023-05-24 05:48 UTC by DanBondarenko

Overview:
* Updated the database schema to support archiving and future deactivation. I deleted the existing `status` column no longer made sense, since the status is now computed from the values of other columns.
* Created methods for working with statuses in the `InstitutionUser` class.
* Created a scheduled nightly job, which deleted roles of users who have become deactivate (runs midnight Estonian time i.e. immediately once new users may be considered deactivated).

This refactoring was done as part of the following tasks:
* https://github.com/keeleinstituut/tv-tolkevarav/issues/139
* https://github.com/keeleinstituut/tv-tolkevarav/issues/145
* https://github.com/keeleinstituut/tv-tolkevarav/issues/147

Before merging, the "base branch" of this PR should be changed to `main`. For optimal merging, this branch should be merged AFTER https://github.com/keeleinstituut/tv-authorization/pull/27, but before any of the other ones.

If you want to see an example of the "finished product" with all of these branches combined, check out [the `feat/#139,#145,#147/combined` branch](https://github.com/keeleinstituut/tv-authorization/tree/feat/%23139%2C%23145%2C%23147/combined).

2023-05-24 08:10 UTC, kadmit requested changes

2023-05-24 08:10 UTC, kadmit commented on application/database/migrations/2023_05_15_121457_institution_user_columns_for_deactivation_activation_archival.php
**[blocking]** @DanBondarenko I would recommend adding indexes for the `institution_users` table. Would be good to have an index that will include `archived_at` and `deactivation_date` as these fields are included in the query for fetching active users.

2023-05-24 16:26 UTC, DanBondarenko commented on application/database/migrations/2023_05_15_121457_institution_user_columns_for_deactivation_activation_archival.php
@kadmit That is a great idea! Thank you for the suggestion. I added it in the latest revision.

2023-05-31 15:59 UTC, DanBondarenko commented
@kadmit Just notifying that I implemented your suggestion, so you may re-review whenever you get time. :)

2023-06-02 09:18 UTC, DanBondarenko commented on application/app/Console/Kernel.php
> +            ->daily();
The `DetachRolesFromDeactivatedUsers` job behavior is not affected by server timezone. It compares the current date in Estonia to the date in database  (e.g. `2020-12-12`).

2023-06-02 09:19 UTC, DanBondarenko commented on application/app/Models/InstitutionUser.php
> +            && ! $this->deactivation_date->isAfter(DateUtil::currentEstonianDateAtMidnight());
Could you specify what do you mean by hardcoding the timezone? The timezone is not saved anywhere AFAIK – the database only has a date-only value (e.g. `2020-12-12`).

2023-06-02 09:19 UTC, DanBondarenko commented on application/app/Models/Scopes/ExcludeDeactivatedInstitutionUsersScope.php
> +                ->orWhereDate('deactivation_date', '>', Date::now('Europe/Tallinn'))
Well spotted!

2023-06-05 06:55 UTC, kadmit approved these changes
LGTM

2023-06-05 11:24 UTC, DanBondarenko commented
For future reference, I was requested to make to remove the methods of the `DateUtil` class as there was a concern that it might invite future developers to overzealously specify the Estonian timezone everywhere, which would not be good practice. Therefore I inlined the methods, resulting in a bit of duplication.

2023-06-05 11:29 UTC, DanBondarenko commented
@thenouan Ready for your re-review

2023-06-07 05:28 UTC, thenouan approved these changes

2023-06-07 05:28 UTC, thenouan approved these changes

2023-06-07 05:49 UTC, merged